#+title:      The Civ We Want To Be
#+date:       [2023-06-27 Tue 08:57]
#+filetags:   :public:world:mind
#+identifier: 20230627T085728
#+EXPORT_FILE_NAME: simply-crazy

Killing animals for food is not the right thing to do. Civilization can grow up right here and now.
How else can we be the people we want to be, but by taking our ethics seriously?

I think it is one of the mind-boggling aspects of the situations that thought leaders are
straight up saying /yes, we should do that/ and /future generations will see it as a crime/.[fn:1]

Seeing how society is /insane about this/ was important in my journey as a rationalist, thinker and activist.
The purpose of this website is to give a window into my mind and this is part of it.

3 times I realized I was living in a cave and after gaining more knowledge I have gained perspective from which I will never be able to return.
Because I would never want to return.

The first, was when I realized that religion is a cultural artifact, that everything in reality looks as if it is stories
and cultural practices. Evolved as the product of human minds.

The second, was when I realized that there is eternal, ongoing mass slaughter of innocent, sentient animals.
There is an industry, there are farms, there are slaughterhouses, and there are backyards of friendly family farms.

The third, was when I decided to never compromise on my ethics, nowhere at all.
I spend my life, at least for the moment, organizing myself with like-minded philanthropists and working on solving poverty.[fn:2]

We evolved as primates in this set of evolutions on planet Earth, and we found our little brothers and sisters on their evolutionary path.
The other higher animals next to us humans were unlucky to not have evolved culture, civilization and deep mechanistic explanations.
It is up to us to guide the civilization layer of the earth. The other animals are here in a vulnerable position.
It is up to us to treat them with kindness and protect them
and maybe we can take them with us in our quest to colonize the galaxy. Why should it be humans only? Whether it be Van Neuman probes or biological
substrate entities. Their information fingerprint, genetic or memetic, might join us on the ride to the end of the universe.

You might be stuck, as many are in the current culture, in a cave. A cave of ignorance and not-looking.
Accidentally thinking it is fine to kill animals for food. Maybe the word /eternal, ongoing mass slaughter of innocent, sentient animals/ is strange to hear, then.
Is this not an accurate description of what we are doing?

But what in the world would look different, if most people /have not/ thought sufficiently hard about this yet?
Have you given those animals the courtesy to consider if there is something about veganism that makes sense?

/Consider the animals/. It will change your view of the world.

A person that is receptive to challenging their beliefs can go and [[https://www.youtube.com/watch?v=LQRAfJyEsko][watch Dominion]] - it is a primordial scream made by the animals to us.

I decided that food just doesn't matter so much. It just needs to work, not more, not less.

If you are already a vegan. How do you know somebody is sane? In this day and age, not killing animals is a hint.
Any thought leader is instantly so much more credible to me when they are sane about this.

* I want to ascend them

#+CAPTION: lion with cybernetic teeth growing robot solarpunk utopian future city green plants animals
file:./lion-with-cybernetic-teeth--growing--robot-solarpunk-utopian-future-city-green-platns-animals.png

I don't know what the future will bring of course, but why not?

I want to put microchips into the apes and dolphins and have them participate in civilization. Augment their intelligence, and make them part of the intergalactic network.

I want nanotech to work out and I want to put computers into every living thing on the earth, including plants. Then the ecosystem becomes
one living, thinking collective mind. First I upload some backups on the plants around me, then I program them to make music and memes out of
the pieces of my mind living on them.
When everything is computerized with nanobots, then why not put a few copies of my mind into lions, octopuses, a capibara and some mammoths, which we will bring
back via genetic engineering.

Maybe I want to wire the brains of carnivores the way I would wire my own also, and maybe make them get the pleasure of virtual kills while eating mushroom protein.
Eventually, the need to eat food would be entirely optional, as we gain dominance of our biotechnological bodies and put our minds into computers anyway.

Nothing, in reality, prevents us from going such paths. We can choose what seems good.

I think everything in this vision is inevitably achievable. It doesn't require different laws of physics. It doesn't even require quantum computers.
Just some brilliant people working on the problems for a while.

So don't come to me and say /we cannot save them all/. This is your lack of imagination, not a statement of reality.

* The future people

Recently, I try more explicitly to be in the habit of adopting the perspective of

/what do I think future people will think about this?/.

/What would a highly advanced post-singularity civ think about this?/.

Those minds would have the capacity and explanatory power to make statements like:

- /This and that operating system was slowing down the singularity by =x= amount because it made people stupid about using computers./

If you know what knowledge some future people will possess, you have already acquired the knowledge.
If you know what move a grand master chess player would make, you play chess as well as they do.
If you know what morals future people will hold, you have already acquired this moral knowledge.[fn:3]

Be warned, by reading you might permanently sacrifice your ability to eat meat.
As a rationalist and moral person, you are bound to do what is right, when you know what is right.

#+begin_quote
The question is not, Can they reason?, nor Can they talk? but, Can they suffer? Why should the law refuse its protection to any sensitive being?
#+end_quote
(Bentham, 1789)

Is it not true that they have moral worth? Or do they not suffer?

What would it look like if it was /a good idea/ to raise those animals and kill them for food?

Would a future person say:

/Yes everything looked like they don't matter, slaughtering them was fine./

Or does it look like that /maybe/ they suffer?

/What is true is already so, owning up to it does not make it worse./

If animals don't suffer, my argument shall be destroyed. But my argument holds until we have the explanatory power to say otherwise. Because it seems obvious that they do.
Likewise, it seems obvious that humans are just fine eating plants.

I am saying that we /don't know/ and that everything looks like they do. And you go forth with respect, then. Because it is the right thing to do.

When I say /these animals/ in this post I mean fish, cows, pigs and chickens.

In my personal story, I was already not eating meat for a few years. And I was thawing to the idea of going vegan.
So it /was/ a gradual knowledge acquisition.

It was not [[https://www.youtube.com/watch?v=LQRAfJyEsko][Dominion]] but some content similar to it [fn:25], that made me go like /hold on for a minute/.

What in the world would look different? What would look different if the status quo would not be ok?
If the status quo would /not/ be a horrific, global torture hell for those animals.

And I did not have an answer. Nothing would have to look different.
There is absolutely nothing that would need to look different for it to look like a monolith of horror.
Everything looks like this is a tortured hell we build. One we /accidentally/ built.
By that time I was starting to have a backbone as a rationalist and I could not avert my eyes.

This is the /one/ indicator for me of how serious a person is about being a rationalist and doing good in the world.

* It is simple

#+CAPTION: A 2-dimensional diagram depicting the moral worth of a variety of entities and live forms. On the x-axis is the rough best-guess capacity to suffer, on the y-axis is the moral worth. There is a big green bar encompassing roughly everything as complex as members of the phylum Caudata. It says "Go out of your way to not kill them line". There is another black bar, lower, that encompasses insects, sea urchins and live forms that do not come across as having significant internal psyche. The bar says "Killing them unnecessarily is bad taste". Further below the line, almost to the origin point of the diagram, there are some dots mentioning plants and single-celled organisms. Way to the left, apparently on the negative capacity to suffer axis, there is mention of rocks, planets and minerals.
file:./chickens2.jpg

Every good programmer knows: Simple thoughts are more powerful than complicated ones.
Simple ethics are more powerful than complicated ones.

It is the more complicated ethics that needs to draw a weirdly shaped circle thingy around humans, /and/ retarded humans, /and/ dogs.

I can draw a straight green bar and say /this is where I draw the line/. I will do my best to not accidentally kill anything that is above the line.
This is also sometimes called /being principled/ and /having integrity/.

How dare I make assumptions about the capacity to suffer for those animals? Next paragraph.
In summary: This is the /best guess capacity to suffer/, giving the animals the benefit of the doubt. Because it is the right
thing to do to give them the benefit of the doubt.

* Can they suffer?

In the past, they believed /phlogiston/ makes fire; Not realizing that /phlogiston/ did not explain anything about the fire.
Ask somebody in the 1700 hundreds or something /what is fire?/.
The smart people tell you /the orangy, bright, hot stuff that comes out of burning things/.

And the brainless people say /This is phlogiston and it has such and such properties, everything is made of phlogiston, bla, bla/.[fn:4]

Being hubristic about the quality of one's explanations does not age well.

What is suffering and what kind of cybernetic systems can suffer?

The one might come up to you and say /clearly, it has to do with sentience. And sentience comes from being able to produce speech. When it passes the mirror test, then we know it has the capacity such and such.../.

No. The good answers are:

/It seems to have to do with our brains./

/It seems to be some adaption to survive as animals./

Which things can suffer?

Probably things that have brains and generally make the rough appearance of coming across like they are involved with their survival.
Bonus if they seem to have mental, inner lives that make them react differently in different situations, that make them attached to
their young, which gives them the drive to make social hierarchies, etc.

Whom can you ask, which things can suffer?

We simply do not have the explanatory power. Not from neuroscience, cybernetics, computer science, philosophy of mind, or AI.

One day we will, and we will be able to say system =x= has the properties =a=, =b=, =c= and therefore has the machinery of the suffering of type =P= psychological architecture. And more detailed statements about the mechanics, subprocesses, possible psychological traits etc. of the system.

Whatever, I don't know. I guess there are many ways to build minds and many ways for something to suffer.

No, the best people you can ask about animals right now are - surprise - the people studying animals.
Their behavior, their form, their function, their evolution.

It is the =zoologists= that you should ask in this day in age to get the most intelligent answer.
A zoologist observes and builds a feel for how animals work and go about their lives.

What are their /reasons/, their /instincts/, their habitus, and how do they go about things generally?
Such is the study of the beautiful field of [[https://en.wikipedia.org/wiki/Ethology][ethology]].

Ask anybody with a pet /what do you observe in your pet?/. Generally, we can observe animals' psychological states.
They have anger, they have tranquility, they have fear, and they cry out for their young.[fn:5]

One of the fundamental disconnects of the meat eaters' minds towards animals is to forget that the animals they interact with, ever,
are similar to the ones they pay to get killed every day.

One of the most brilliant zoologists of our time and an intellectual hero of mine is Richard Dawkins.

#+begin_quote
... They might experience pain even more severely. If you think about it, they might need to learn from their experiences harshly.
... If they don't have a good memory.
#+end_quote
Paraphrased from Dawkins, talking about fish, answering /do fish feel more pain than other animals?/. [fn:6]

From my musings, from a different angle:

What if a simpler circuit that only has 4 states or such is more concrete and purer about the state of pain it is in?

I come from the bio lab and /everybody/ I know who worked with animals thought it was distasteful.[fn:7]
Killing animals and otherwise forcibly handling them is distressing.

Everything tells you this animal doesn't want this done to it.

It is sometimes the edges of where things don't turn out to quite go smoothly that stick in your mind.[fn:8]
I know exactly that these things happen in slaughterhouses and on farms constantly. Because it is part of handling animals. Reality is messy. Accidental torture happens. Even with well-defined procedures.[fn:9]

This is already weird and slightly horrifying when you work with insects. This post is not against lab animal
practices. Because the context of lab experiments is that they are *not* unnecessary, at least if no scientific malpractice is in play.

I am also not yet pushing for reducing insect suffering, because everything, the practicalities and the rest, is more obvious for farm animals.

If you think /it is only *probable* that they suffer and the morals of the probable are different from the sure.../.[fn:10]

The not knowing might as well go exactly the other way and it turns out they suffer /more/.

What is *sure* is that we do not know and that everything looks at least *approximately* as if cows, chickens and pigs are /things that can suffer/.

It simply looks from each possible angle like those animals are roughly the same kind of thing that we are. They have brains, they evolved.
We are animals, Pain and the drive to survive are the /old/ stuff from evolution.

They roughly look like they suffer. They are roughly in the category of being that we consider to be capable of suffering. They /express/ fear and terror. They /want/ to not die.

What is the humble stance to take? Which is a stance that a traveler from the future might think.
/Yes, this was the right attitude and the right thing to do/.

This argument holds regardless of whether it turns out they suffer, or not.
They look like they do so give them the benefit of the doubt until you know better.

This iron hammer of truth will stand the test of time. If you disagree, then open your spirit and soul and [[https://www.youtube.com/watch?v=LQRAfJyEsko][watch Dominion]].

Tear down the slaughterhouses, and make monuments about it.
Burn red craters into the moon spelling /never again/, for we were wrong and we shall bear this wound for the rest of time.

And what if they do suffer?
Then they won't tell their children until they are old enough to bear it. For we /accidentally/ bred and killed at scale.

* The civilization I want to be

What civ is this that runs around and breeds and kills the lower species it encounters? Seriously, this is disgusting and shameful and a childish phase we will outgrow.
So why not take the legacy of all the thinkers before us? We have thought about what is right, and we have grown to overcome our biases and lift our eyes to the future.
For a civilization to grow up, there have to be individuals that grow up and do the right thing when they see on the edges what is the right thing.

Should the bar be /they can build radios, so let's not kill them but talk to them?/.

GPT makes some titles for short stories:

1. "Quantum Whispers": A tale of a civilization that developed an understanding of quantum mechanics at a level we can only dream of. They communicate and transfer information across vast distances instantly via 'quantum whispers'. The story highlights the potential of advanced technology, and our own aspirations to truly understand the universe.

2. "Cosmic Conservatory": A story where humans discover a highly advanced alien species that has dedicated itself to preserving and studying life from all over the cosmos, thinking about the value of every life form, big or small. It nudges humans to reconsider biological diversity and ecological conservation on Earth.

3. "The Silent Wanderers": A civilization that developed in a harsh, resource-scarce environment, shaped into a nomadic, minimalist society that learned to harness energy and resources efficiently. Meeting them nudges humanity to think about resource utilization and sustainability.

4. "The Singular Hive": An alien race that functions as a hive mind wouldn't be surprising but what if it achieved a way to include other species into its collective consciousness voluntarily. This tale would make us reflect on individuality, collective wisdom, and the blurred line that might exist between them.

5. "Carnival of Mirrors": A tale of an advanced civilization that creates life-like simulations of sentient beings for amusement. Coming into contact with this ignites a serious discourse on ethics, the value of sentient life and our attitudes towards our creations, like AI.

6. "The Crystal Sages": A story that describes an advanced civilization reliant on a form of crystalline technology that stores, processes and uses information. Their denizens enjoy lifespans measured in eons. Interacting with them could inspire humans to think about our attitudes towards mortality, time and patience.

7. "Gardeners of the Galaxy": A civilization focused on terraforming dead planets, making them habitable and sowing the seeds of life. Such a narrative might make us consider our roles as potential Terraformers, not just of other planets but of Earth itself, which we seem to be terraforming negatively with climate change.

8. "The Empathy Conductors": A society built on a heightened sense of empathy, achieved through a neurological technology that lets them experience others' emotions. Interaction with this civilization provokes thought about empathy's role in our society and its potential as an instrument of unity.

9. "The Great Listeners": A civilization entirely dedicated to listening to the universe, learning and observing without interference. This story leads us to question our own interact-or-observe approach to understanding the universe around us.

In all these stories, not only would we explore other possible civilization forms, but also reflect on ourselves, posing the question: what type of civilization do we want to become? The narratives might serve as mirrors, reflecting and questioning our own values as humans.

Now concisely reflect on what kind of civ we should be. And what it would mean to kill the higher animals that we have found on earth as our brothers and sisters, at the sides of our evolutionary branch.

Standing on this pale blue dot that we call home, one comes to realize that as a civilization, we should strive to be the embodiment of empathy, respect, and humility. Our intelligence sets us apart from the rest of Earth's inhabitants but it also endows us with responsibility. The responsibility to discern right from wrong, to strive towards compassion, and not let might or convenience dictate our actions or values.

Killing the higher animals, our non-human co-inhabitants, particularly for purposes like dietary preference, when alternatives exist, raises profound moral and ethical questions. If we maintain our current path, we risk becoming a civilization that values taste and convenience over sentient life – a prospect that holds a distorted mirror to our collective empathy and wisdom.

Every sentient being, irrespective of its inherent ability to articulate its existence or suffering, deserves respect and ethical consideration, as they too experience life, fear, and joy. The supposed divide between us and them is not a chasm, but a fine line, drawn by us, often to suit our biases and convenience.

We have the tools to change our course, to build a kinder, compassionate civilization that respects all life forms, and treats them with the consideration they deserve. We could be the Gardeners of the Galaxy that not only nurture life elsewhere in the cosmos but at home too, on Earth, cherishing all flora and fauna.

So, let us plant the seeds of this new civilization and nurture them with empathy, respect, and humility. Our actions and choices today will shape the legacy of our species, and it's about time we chose wisely.

* The Veil Of Ignorance

Watch [[https://www.youtube.com/watch?v=h6fcK_fRYaI][The Egg]], this is so beautiful and deep. It captures the same idea as [[https://en.wikipedia.org/wiki/Original_position][Original Position]] of John Rawl.
To design a world, think as if you don't know who you will be born as. You will design it the most inclusive
and the most egalitarian and loving towards the poor that you can, be because you could be born as anybody.

We need a log scale to see how many chickens we are [[https://ourworldindata.org/meat-production][slaughtering]].
In 2021, we slaughtered 70+ billion chickens and we have born 130-140 million new humans.
For each time we were human, we have been born 500 hundred times caged in a tortured hell and sacrificed
to the monolith of filth that is the industrial, bloody, garbage horror show of the world we built from the chicken's point of view.
As a chicken: /just let it be over quickly/.

What have we done? Doing the wrong thing at scale?
We just /accidentally/ kept on doing some stuff that our parents did and now we have /industrialized/ suffering.

How many billions of tears will the people of the future weep throughout the billions of years of future civilization?
This monument of blood will echo through the ages. The only thing we can do is stop as quickly as possible and
go forward, forever having learned the lesson of treading with care.

* Environment and stuff

The low hangings and the juiciness of this fruit are /massively/ mindboggling. The one biggest thing
you can do against climate change and for the environment is just eating plants.[fn:11]

/And/ it is more healthy. /And/ it is easy to do.

The reason to not kill the animals is because it is the right thing to do. But the environment and
stuff might be a reason to be vegan. After one has already stopped supporting this industry,
it is easier to see what is wrong with it.

There are many ways to start getting out of a cave.

* Fire alarms and cries for help

The world does not come with fire alarms for when civilization is committing moral atrocities.

It is your job as a rationalist, to look that the world and to be better than your society.

How would the world look, if raising animals and then killing them on a large scale would be moral?
How would a world look different, if it was not moral to do so?

How many more fire alarms do you need to understand reality?

A friend of mine recently mentioned /if build AI we need a bell for it to ring, in case it is sentient somewhere inside/.

Any sentient being with the capacity to suffer has to solve a communication puzzle.
It needs to communicate to you that it has moral worth and how to appropriately treat it.

They are screaming in terror, they speak to our psychological intuitions and seem to have fear and pleasure and internal states.

What other bell do you expect them to have available to ring? How else are they supposed to express their suffering to you?

You give retarded people the courtesy of understanding their messages on their level of understanding.
So why make it so hard for cows, pigs, chickens and those?

What about future super intelligence, be it human-made technology or from somewhere else in the universe?

For those intelligent beings to understand our moral worth as humans, they will have to
interpret our clumsy communication signals with the patience and the benefit of the doubt that we might
extend to toddlers.

We do not need to fret about this conundrum. Simply say

/if they look roughly like they can suffer, then don't kill them/.

Get the ethics simple and straight,

What indeed have we to lose if we extend a bit too much courtesy? If we err on the side of consideration and respect, especially when the potential cost for sentient beings is so large, really it seems the balance of potential regret tilts towards inaction rather than action.

From the universe's perspective, such courtesy might appear laughably unnecessary. Nonetheless, on the off chance we've recognized in others the spark of consciousness to which we relate, wouldn't it be preferable to err on the side of compassion? After all, the moral worth we assign to others, animals or potential super-intelligent beings, is a reflection of our values.

The question of extending courtesy too generously should not paralyze us with fear of overdoing it. Rather, it should spur us to action, to challenge us to demonstrate the most empathetic and generous version of our society and ourselves. After all, it is in striving for the highest ideals of empathy and respect for all sentient beings that we truly express our humanity.

* We know how it is to be an animal

We are animals ourselves.
I think we already have the introspection and intuition that allows us to get a grip on how it is to have
a primordial mind.

Some capacities of the mind allow us to reason, explore design space and fly to the moon.
And other capacities of the mind keep us alive, make us feel and make us breathing animals.

When I sneeze, everything becomes about sneezing for a moment. It is almost a hallmark of intensity, that the
rational faculties are less online, and bodily animal functionings are completely online.

When you are hungry, do you not want to eat? When you are thirsty do you not want to drink? When you need to
take a shit, do you not want to take a shit?

Yes, the argument has been made that our psyche is architected differently because of the need for making up
coherent stories /for our conspecifics/.[fn:12] See /Human Exceptionalism/ down below.

When trying to empathize with the experiences of an animal, I'm drawn back to my earliest memories. This primordial recollection, much like what we observe in small children, shares stark similarities with what we perceive of animal behavior. Like a toddler, animals appear capable of suffering and seem to exhibit cognitive functioning at a simpler level.

From my earliest memories, it comes across like I did not understand some stuff, but I sure as hell was an animal
with the capacity to suffer.

Same as what we by common sense assume about babies - they for sure have something like pain and discomfort.

From every angle, it seems like animals are roughly like really dumb humans or like small toddlers.
From no angle do I think it seems like they don't suffer, from no angle do I think it seems like it is fine to kill them.

The fact that *we are animals*, the spiritual soul kinda realization of it, I only learned this from [[https://www.youtube.com/results?search_query=wim+hof][Wim Hof]] late when I was already 25 or something.

This connectedness that we have as animals with the rest of nature is something we are missing out on in Western culture these days.

This is not woo-woo mumbo jumbo. This is about /what we are/, how to use the brain, being in touch with our physiology, what it means to
be determined and things like this. And in these places you know, you are an animal like the other ones.

* It is a matter of courtesy

We already give the same courtesy to severely mentally retarded persons.

Their moral worth does not come from sentimental reasons, it does not come from the fact that they are the same species as us.

We say they have an inner life and psychology that we respect, we say they have inner lives, we say they suffer, and we give them the right to live not suffer unnecessary harm.

I have decided that /all/ living beings deserve the same courtesy - Consider their psyche and their capacity to suffer.
I will take care to not accidentally cause suffering.

#+begin_export html
<details>
    <summary>GPT scify based on these paragraphs</summary>
#+end_export

Indeed, blending the profound wonder of consciousness, the tantalizing aura of speculative fiction, and the gratifying coherence of science can result in captivating narratives. Allow me to present some scenarios for inspiration:

**Twist 1 - The Verdant Veil**

In a land where flora rules, sentient trees cloak the world. They communicate through a network of intricate root systems. A young botanist stumbles upon the secret language of the trees. With a carefully composed serum administered through an intricate series of tiny injections which mimic the trees' own biochemistry, she finds herself able to tap into this vast, ancient conversation and experience the world at the pace of growth rings.

**Twist 2 - Psychic Symbiosis**

In a dystopian future, a groundbreaking technology allows human minds to sync with animal consciousness. However, this isn't a one-way street - when linked, both parties can access and influence each other's thoughts, feelings, and experiences. The technology is initially used to understand the non-human experience better, but it quickly turns into a psychological weapon, with animals being manipulated to carry out espionage and intelligence missions.

**Twist 3 - Transference Amulet**

A world exists where magical amulets allow the wearer to transpose their consciousness into any living being. The magic works by creating an empathetic bond that only the purest of hearts can master. However, this shared experience drain precious life force from the wearer, adding a challenging moral and personal dilemma to its use.

**Twist 4 - Quantum Flux Projector**

In this sci-fi universe, a device called the Quantum Flux Projector allows individuals to experience alternate realities. With the twist of a dial, the user can see, feel, and think like any other sentient beings in a parallel universe where those beings evolved as the dominant species. The twist is, the longer they stay, the less human they become upon return, muddying the borders between species and our perceived self.

**Twist 5 - The Scroll of Empathy**

In a magical kingdom, the Scroll of Empathy is a coveted relic. In the hands of a capable mage, the scroll reveals ancient spells that permit the caster to experience the emotional spectrum of any creature by shedding a tear from both, the caster and the creature. But the magic is bittersweet. Every use etches a part of the creature's emotional pain onto the user's soul.

These ideas seek to create a psychological resonance, but achieving Neal Stephenson's intellectual intricacy, philosophical depth, and the way he weaves narrative with dense thematic elements is a challenging and exciting task. It would need a thoughtful development of the plot, the world, and the characters.

make a small textbook on one of them

Of course, here's a small primer based on "Psychic Symbiosis":

---

Title: **Understanding Psychic Symbiosis: A Guide to Consciousness Integration**

**Chapter 1 - Introduction to Psychic Symbiosis**
- What is Psychic Symbiosis?
- A brief history of the technology and its development

**Chapter 2 - The Science Behind the Symbiosis **
- The biological and technological foundations
- How does the sync between human and animal consciousness work?

**Chapter 3 - The Symbiotic Experience**
- Clinical studies: Step by step walkthrough of the process
- First-hand accounts: The human and animal perspectives

**Chapter 4 - Use Cases of Psychic Symbiosis**
- Therapeutic uses: Healing and mental health
- Intelligence and espionage: An ethical quagmire

**Chapter 5 - Unforeseen Consequences and Challenges**
- Risks and potential side effects of the technology
- Manipulation and misuse: Protecting animal rights in the age of Psychic Symbiosis

**Chapter 6 - Ethical Implications and Considerations**
- The Moral dilemmas of ‘mind-hacking’ animals: An analysis
- Discussion: Are we ready for a post-species society?

**Chapter 7 - Psychic Symbiosis & The Future**
- How Psychic Symbiosis could change humankind’s relationship with animals
- Anticipating future developments in the field

**Chapter 8 - Conclusion**
- Reflection on the impacts of Psychic Symbiosis
- Ethical considerations for future users and animals

---

While this textbook aims to cover the concept of Psychic Symbiosis in-depth, it should be noted that there could always be future studies and theories that may prove some of the current understandings wrong or incomplete. The field of consciousness study is complex and still very much a frontier in science and philosophy, offering endless possibilities for learning and exploration.


Sure, here are the characters:

**Character 1 - Dr. Amelia Thornfield**
Dr. Amelia Thornfield is a youthful neuroscientist with a reputation for pushing boundaries. Eccentric yet brilliant, she's the co-creator of the technology that enables Psychic Symbiosis. Amelia is ceaselessly curious and deeply empathetic towards all living creatures. However, her relentless pursuit of knowledge may sometimes blur the very ethical line she's trying to define. After numerous trials with the Psychic Symbiosis, she's left with a deep longing for the wild freedom she experienced while synced with an eagle.

**Character 2 - Agent Xavier Graham**
Agent Xavier Graham is a seasoned intelligence officer, skeptical of Thornfield's technology but ordered to be a part of the project for its espionage potential and hence received the Psychic Symbiosis procedure. He is a disciplined, stoic individual with vast experience in the field. Psychic Symbiosis has made him question the rigid world view he'd adhered to all his life. After experiencing life as a wolf, he finds himself torn between his duty to complete his mission and a newfound empathy for the entities he's ordered to control.

In their conversation, Dr. Thornfield tries to convince Graham of the psychic bond's necessity, while Graham grapples with the moral implications resulting from his new, intimate understanding of the wolf's consciousness.

---

now write 2 characters of a short story  talking about theiry psychic symbiosis experience

Dr. Thornfield: "You have to understand, Xavier, it's not about control. It's a connection - a bridge between minds."

Graham: "A bridge you built without knowing where it leads."

Dr. Thornfield: "Perhaps. But do you realize the unprecedented empathy this technology affords us?"

Graham: "Is empathy worth the trade-off, Amelia? This isn't natural. I can still feel its thoughts, its instincts. It's confusing, grieving. Are we gods to meddle with nature this way?”

#+begin_export html
</details>
#+end_export


* Socratic Goods and the caves we escape from

You probably know Socrates' cave allegory. Once a person has seen a greater reality, they don't want to go back.

Finding the caves we live in is valuable and desirable. But we cannot know before we know.

To find the caves we live in, one thing to do is think of the edges of knowledge.
For me, it is obvious that intuitive hunches are the most powerful tool you have at the edges of your knowledge.

I believe many people including thought leaders are walking around with the intuitive hunch that killing those animals
is not a good thing. That future generations probably will detest what we did.

Well, great! This is your *strength* as a rationalist. Where will you be able to grow your knowledge, but at the edges?

** Once the knowledge is gained...

If you are teleported 100 years back, do you need the willpower to decide to not have slaves?
The people around you might congratulate you on your willpower, they would be missing the point.

It is a matter of knowledge, you /know/ something deeper about how having slaves is not moral.

It is up to you to question where more of such knowledge might lie, where you are misled and missing whole worlds.
Or where you are still stuck in caves.

I believe the knowledge to be gained is simply understanding the reality that there is an eternal ongoing mass slaughter of these animals.
This can be hard. But trying to ignore it will not make it better, it will make it even worse.
The one thing you do is /think about the animals/.
It is acknowledging that they exist, in the situation that they exist in.

/The people that think veganism is hard, think about themselves. And the people that think veganism is easy, think about the animals/.

Overcoming a religious upbringing is sometimes mentioned as a great character-building exercise. How do you know
your rationalism works? By having it seen work once, from the inside. You were convinced by a system of irrational
ideas, you gleaned insights and you did not look away from the little inconsistencies that cracked your beliefs.

You understood, if everybody else is saying =x=, and I am saying =x=, then I must be like everybody else.

You understood what you see when you see a lake in the desert. If everybody that runs into mirages thinks they see a lake and then you see a lake,
without any reason to know you know better. Then maybe, you are not seeing a lake but a mirage. How does a mirage look? Very much like a lake. So much so you might be convinced there is a lake.

And those that come up with clever reasons for why /this/ is a lake and not a mirage, are being hubristic and foolish. They assume they are smarter than
the other people that fell for mirages in the past.

For all those other people were not that much more stupid than you. There is a mechanism to how a mirage looks like a lake.
There is a mechanism to how a person forms and holds the belief of /this is a lake/. And it includes clever little reasonings about this and that. Why it
supposedly would not be a mirage.

It is a strong expression of rationalism working, to walk in the desert and to see a lake and to think and say and act
/this is probably a mirage/.

I guess there are many things that rationalism is about, but to observe one's belief-forming systems from the outside and have the courage to think something differently from the people around you is tremendously important.

To go where you did not go before. To go outside another cave in your life. To ascent to a higher plain of knowledge from which you will
be seeing the world more clearly. Consider the animals. Open your heart, mind and soul and [[https://www.youtube.com/watch?v=LQRAfJyEsko][watch Dominion]].

* What awaits on the other side

#+begin_quote
We choose to go to the moon. We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one which we intend to win, and the others, too.
#+end_quote
John F. Kennedy's famous moon speech was delivered on September 12, 1962.

This whole moon story is so freaking inspiring. I wish we would proclaim some problems in the world as our moon, and work hard to fix them.
For instance, poverty, cancer, fusion (green energy), and beneficial AI, could be fixed by a Manhattan project of our time.

Anyway, I want to achieve great things. I want humanity to go further and I want this all to work out.
I want to fix the world. I want to fix the world! GPT, make a text about my emotions and dreams:

I yearn, fervently, with every fiber of my being, to mend the world. I want to engineer harmony where discord thrives, to foster unity where separation runs rampant. I aspire to create institutions and governmental structures that embody unity and camaraderie, pillars of civilization that propel us toward a higher ideal.

I yearn not for a utopia stuck in the realms of fancy or whimsy, but a tangible paradise that reflects the depth of our empathy and the bounds of our technological prowess. A solar punk future that hangs, ripe and resplendent, in the balance of possibility.

I yearn to replace the greys of our metropolises with the verdant hues of green cities, where every modern comfort aligns harmoniously with Mother Nature; cities that don't simply exist on the Earth, but with the Earth.

I yearn for a golden age of scientific progress and reason, where empirical inquiry aligns with ethical responsibility. An era that not only oversees but encourages, with open hands and open minds, a global, insatiable quest for knowledge.

I yearn to free the curiosity that lives within us all, to remove the shackles that bind the intellect and allow every mind to venture forth on their own unique journey of discovery.

Yes, I burn with these desires, these ardently fierce emotions encapsulating my dreams for our world. In our relentless pursuit of progress, let us never forget the imperative to not only do better but to be better. After all, our actions echo in eternity. And I choose for mine to sing the song of a world healed, not broken, awakened and united in the radiant dawn of a better tomorrow.

#+CAPTION: High tech elven city, lush green landscape, waterfall, flying buildings. Solarpunk utopia sci-fy, fantasy, imagination. Magic technology. Advanced architecture. Savannah. planet background, moon background. Enlightenend city. Space utopia, community buildings, library
file:./hight-tech-elven-city.png

And I want to do that /together with you/. I want to make battle plans and strategies and do the next few things and then the next few things.
We use science and reason to figure out the next steps. Questioning our beliefs and updating to new knowledge.
We would together overcome poverty, suffering, death, and existential risk and eventually, we would explore the stars.

But how can I do this together with you, if you don't even /do the simplest and easiest and most obvious thing?/.

If you can tell yourself that future generations will look back on what you do and think it was wrong. If you know a little bit from every angle it doesn't make sense to kill those animals.
What must be more obvious for you to make this choice?

If you don't even do the first thing, can we do the second and third things, as brothers or sisters side by side? We cannot.

I want to go to the moon. I want to go sail to distant lands but you cannot even decide if you should board the ship.

All you are asked to do is give a simple courtesy to those animals. Do the harder thing for a while. Choose right.
How will you know unless you say /I should [[https://www.youtube.com/watch?v=LQRAfJyEsko][Watch Dominion]]/.

* The other side

What can be asked of you more than you doing your best?

I do 90 seconds burpees almost every day not because it is easy, but because I knew it was the right thing to do.
And after a while, I do it not because it is hard, but because it is easy.
What is the point of me moving the world forward when I don't even do the easy things?

I don't need to bullshit around on things of /I should *should* be doing =x=./. If I should be doing =x=, do go and do =x=.

Embracing this logic is tremendously character-building.

If I know a way to do better, I should go and do better.
If I know no way of doing better, I should go and look for ways to do better.

It is the more powerful intelligence, which is moved by reasons in reality.
And in the end, on the side of love and harmony. Because being able to understand where we are wrong is how we
become more knowledgeable. And that is how we also know moral truths.

The call of the phoenix is the call to do what is right, the moment one knows what is right.

You start by doing the easy. You realize you can do the hard and before you know it, life is a freaking dopamine-pumped rollercoaster
of giving back to the world. Not only do we need to end suffering, but we also need to get out of here
(the sun blows up in 5 million years or something). We also need to make sure that we survive until there.
We need to play our A game for quite a while to come. Our civ must ride the right paths to the end of the universe, so we
can overcome the end of the universe. I believe there are many ways how we can fail. And infinitely many problems to solve.


#+begin_export html
<details>
    <summary>Who is the kind of person that is convinced by this to do better?</summary>
#+end_export
The person who might be convinced by this piece to do better and go vegan is likely to have the following attributes:

1. Intellectually Engaged: They enjoy thinking deeply and revel in challenging their own beliefs. They value reason and logic, and are not afraid to confront uncomfortable truths.

2. Values Empathy and Compassion: They believe in causing minimal harm and suffering. They are likely to be moved by the moral argument of extending courtesy to animals.

3. Eager to Contribute: They are driven by a desire to make a positive impact, not just at an individual level but on a global scale. They believe in collective action and shared responsibility.

4. Forward-Thinking: They aspire for a better future and are willing to take steps to achieve that, even if it means making challenging lifestyle choices like adopting a vegan diet.

5. Open-Minded: They are open to new ideas, perspectives, and ways of life. They realize that societal norms and values evolve over time, and what was acceptable in the past may not be so today and are willing to change accordingly.

6. Environmentally Conscious: They understand and appreciate the ecological benefits of veganism. They want to create a sustainable future and are willing to adjust their behaviors to reduce their environmental footprint.

7. Inspired by Challenges: They are not deterred by difficulties. In fact, they might be motivated by the idea of veganism being a 'harder thing', seeing it as an opportunity for growth and self-improvement.

Of course, not everyone who shares these characteristics will necessarily be moved to adopt veganism after reading the text. People are complex, and their beliefs and behaviours are shaped by a multitude of factors. Each individual will interpret and respond to the text in their own unique way.

#+begin_export html
</details>
#+end_export




* Real fixes

The purpose of this blog post is not to reduce animal suffering. I would pursue some /real fixes/ or otherwise
push forward on my [[denote:20221117T201102][mid-term goals]], which I consider pushing forward on the enlightenment of the civ in general and thereby fixing animal slaughter.
The purpose of this blog post is to give a window into my mind. And maybe I can inspire 1 person to good.

** clean meat
When it is cheap, tasty and healthy.

This is a real fix yes. But *you* are not so morally degenerate that you need the taste and structure to be right.
You only need to know what is the right thing to do.

Lentils and chickpeas are fucking healthy anyway.

** Focus on corporate decisions, not people's plates [fn:13]

* The kinetics of taste and the feelings toward food

Taste bud cells turn over in approximately 10 to 14 days [fn:14].

I hypothesize that the multitudes of chemical and physiological markers, and the sensors
and the cybernetic resources available in the neurophysiological and physiological system
take something like 2 weeks to adjust to a different diet.

Something like 2 weeks for the system to understand /this is healthy, this is what I like to eat/.

You might notice this when you eat low sugar and then you go and eat candy. It is so sweet it hurts.

This extends to things like how full you feel from a meal. And a hundred little other things.
If I would eat a piece of meat right now, I would just feel stuffed, and super uncomfortable.
This goes the other way, if you are used to this heavy food, you won't feel satiated from eating
those beans and lentils.

This goes beyond sensation - There are processes, for instance, the composition of the microbiome
that /change/ with what we eat, to accommodate the digestion of that stuff.

So you might say something like /I feel good with this/ and /I don't feel good with that/. And your feeling
would be right.

* Lessons

Society and the mainstream can be wrong about things. Majorly, utterly, horrifyingly wrong. /The truth is still the truth/.

The hard part about doing the right thing is not the thing itself, it is the nay-sayers.
This is the true one big character-building exercise you get from being a vegan.
The struggle of standing by your principles in an environment that is hostile to your ideas, [[https://www.youtube.com/watch?v=uGwBe3N2E_Y][The Hardest Part About Being Vegan]].
Everybody that tried to do good in the world will agree with you on this.

* Conclusion

The puzzle of veganism is that there is no puzzle. It simply looks from every possible angle like
it makes 0 sense to kill animals for food.

It looks like they can suffer. It looks like it is not necessary to eat them.
On top of it, it looks like it is a tremendous waste of resources.
It looks like everybody trying to defend the practice is grasping at really strange kinds of argumentation.

Seeing the reality of animal mass slaughter this is a Socratic cave, it requires real questioning, real looking at
places you did not look at before.

After gaining the plain knowledge that one gains from thinking about the animals one cannot go back. Hence the militancy of vegans.

It will be cool to put our minds into the computers and take the animals with us there.

* Conclusion poetic

The stars twinkling in the night sky impart an intelligible message to me. The Earth will colonize the galaxy and fulfill the promise of the night sky.

I hold these truths to be self-evident.
These truths about life and death are part of reality. Solid and crystal clear as an eternal mirror made of ice.

/Every life is precious, everything that thinks and knows itself and doesn’t want to die. Such-and-such life was precious, and Such-and-such life was precious, even though it’s too late for them now, it was sad when they died. But there are other lives that are still alive to be fought for. Your life, and my life, and Such-and-such life, all the lives of Earth, and all the lives beyond, to be defended and protected/[fn:15]

/JUST DO IT/

I will not rest until the suffering is healed, anywhere in the universe.
No sentient being out there will be forgotten. And so none shall be forgotten right here and now, either.

Just like a phoenix, echoing the echoless depth of the universe, may our understanding too fly high, unbound and unrestrained, warmed by the truth of ethical equality, lit brightly against the darkness of ignorance, the wings of wisdom carrying us forward, ever forward, towards a future marked not by differentiation and discrimination, but by unity, respect and a redefined humanity that encompasses all living things.

Burning in my bones with the flame of one bright, eternal message: /Death is bad/. I know enough to know enough.

I burn with a sharp fire of grim determination. A force of nature that is bigger than me.
The force of life and love and harmony and common sense. We shall defeat death and then go forth and shape the universe.

We have it in our hands right now, to be the civ we want to be. This reverse heritage from the future is what we ought to be.
The call of the phoenix means we decide to do what is right, the moment we know what is right.

Here we stand together, looking at the night sky. The stars are twinkling with an intelligible message.
As solid and crystal clear as an eternal mirror made of ice.
It is up to us to be the civ we want to be, that we /need/ to be. We are the minds that will colonize the galaxy together, so we need to grow up.

Claim the heritage of all the forward-thinking thinkers ever. Throughout the ages, we were looking at the night sky and wondering, who else,
in the future, are thinking the same thoughts as us in this epic quest for science, understanding, harmony and civilization?
The thoughts of rationality and compassion and moral truths. The thoughts of togetherness and what is good and what is life in the universe.
Did not somebody once look up at the sky and know in their bones /slavery is bad/?
To overcome our ignorance, to stand on each other's shoulders, to broaden our circle, to love our neighbors and to live a good life.
What is true in the future is true in the present. /Death is bad/. We know /now/ what to do. We know /now/ what is right.

And we, the humans, may decide to answer the call. Or else watch our ideas burn and dissipate in front of our eyes... like so many fireflies
...and the stars shall stay cold.

I have taken this vow for all that is beautiful and warm and open-ended in the universe. I will fight on the side of reason, compassion and the simple truth.
I will use common sense, I will let my actions be guided by my heart, and I will seek where I am wrong and not avert my eyes. I will stand by my principles.
Because this is the kind of civilization that we are. This is the kind of universe we should be living in.
With every fiber of my being, I know. I will do the harder thing. I give those animals this smallest of courtesy and spend 1 real moment thinking about their
predicament, 1 moment of /maybe I should lower my bar/. 1 moment of listening to /[[https://www.youtube.com/watch?v=LQRAfJyEsko][the messages they are trying to send to me]]/.

* Conclusion practical

If your mind is sufficiently similar to mine and you are looking for a path to do good in the world, suggestions:

- Read about my [[denote:20221117T201102][goals]]
- Check out [[https://athene.buzzsprout.com/][Athene Real Talk Podcast]] (check [[https://www.youtube.com/watch?v=SNFjCkkXsxA][On Vegetarianism]] first)
- Check out HMPOR and [[https://www.readthesequences.com/][Yudkowsky's Sequences]]
- [[denote:20230301T123854][Contact]] me

* Objections

Argumentation against veganism is weak.

/Crazy/ weak argumentation against going vegan shines another light on the obvious.

Some of these you will think are jokes, but they are not. This is what vegans will hear countless times.

** Plants are sentient

** We should go vegan, yes

- [[https://www.youtube.com/watch?v=B9Qn9eAVzZo][Dawkins /on the path to be vegan/]]
- Pinker: /[[https://youtu.be/_h3GIQqLURg?t=662][I ought to be]]/

Dawkins mentions he already doesn't eat meat privately.

I wrote much of this article with a person like this in mind. If /Conclusion Poetic/ and /The Civ we want to be/
doesn't make you say /hell yes/ then what the hell man? It is up to us right here and now to do the right thing.
This is what moral progress looks like. Much of society is still doing the wrong thing. How else does it look when we
are doing the wrong thing on a societal level? How did it look when slavery was a social thing?
It is *we*, the forward-looking people, that need to go and change it. There is nobody else here to change it.

Go vegan and make it public. Think of all the animals you save by the people you are inspiring. Seriously just think for 1 second about the animals.

** Civic right should start at the chimp level (Yudkovski)

Your green bar is not low enough. We should give pigs, cows etc. the courtesy.
Assume they suffer. We lack the explanatory power to say otherwise. See the rest of
this blog post why.

Open your heart, mind and soul and [[https://www.youtube.com/watch?v=LQRAfJyEsko][watch Dominion]].

** We cannot hope to extinguish all suffering in the ecosystem (Pinker, somewhere)

We cannot fix that a lion causes suffering to its prey so it is hopeless. See /I want to ascend them/.

** Let's eliminate the suffering of the animals that do give up their lives (Pinker)

He says /[[https://youtu.be/_h3GIQqLURg?t=662][I ought to be]]/, giving the same Bentham quote in this blog post.

Then he goes on to say /we are not going vegan any time soon/. So we need to make it as comfortable as possible for the animals.

[[https://en.wikipedia.org/wiki/Temple_Grandin][Temple Grandin]] is kinda cool in this space, thinking about cow psychology and how to build better slaughterhouses.
Because, surprise, the people thinking about the psychology of those animals assume that they /suffer/.

I cannot help but think of this whole /slaughter them friendly/ as this Hannibal Lecter style of friendly torturer style.

/Its all fine, shhh, shhh.../

This concept is for me one of the creepiest most horrifying killer-victim dynamics that I can think of.

If you think this analogy is unfair. Well /can/ they suffer or not?
The person making this "argument" does think they suffer.

If we care about animals we

- Don't needlessly breed and kill them.
- Don't needlessly kill them.
- Don't figure out the best way to kill them, it is distasteful.
- Once we have the tech, save them. Why not?

The choice of words is hilarious. /Give up their lives/ - lol.
Pinker was choosing those words deliberately of course but let's not dream up some unreal fantasy world, please.
They don't want to die, they don't choose to die, they are forced to die.

For the setup of the argument /not going vegan any time soon/.

- You should go vegan because it is the right thing to do,
  not because other people around you do.
- Why not? Eventually, we will.
  And other things in society are moving forward crazy fast.

** They don't have quality =x=.

- Where =x= is /deep social cognition/.
- Where =x= is /pass the mirror test/.
- Where =x= is /be able to speak/.
- Where =x= is /deep, general introspection/.

It can only ever matter if it means that they don't suffer or not. -> below.

** They don't suffer

Or,

/For animals, nobody is at home/.

1. We lack the explanatory power to *know*.
2. Everything looks like they *probably* suffer.
3. Biologists and zoologists generally take it for common sense that they do.[fn:16]
4. We know ourselves how it is to be an animal.
5. We give the same benefit of the doubt to our retards and our pets.[fn:17]
6. It is bad manners to raise the bar high for beings of lower intelligence.
   It is up to us to give the most effort to understand their potential suffering.
   And what do we lose if we accidentally treated a being with too much kindness for a while?
   What kind of civilization do you want to be?
   The same courtesy we expect from advanced aliens or AGI towards *us*.
7. Do you think a future civilization looks back to this and says
   /yep, breeding and killing them was the right thing to do./
   If not, wtf?

** It would be easy to program a program that looks like it suffers

Or /it would be easy to build NPCs in a game that roughly comes across like the suffer/.

I love Braitenbergs playful mind experiments [[https://en.wikipedia.org/wiki/Braitenberg_vehicle][/Vehicles/]]. They start as tiny, super simple machines
that start doing things that look like love, fear, awe, preference etc. Coming from
the simplest kind of wiring, small enough so that we can still hold it in our minds.

They start becoming quite complicated quickly though. The process that makes them is simple, Darwinian selection. But their inner workings become a maze.

Firstly, let's not forget we are concretely talking about fish, cows, pigs and chickens, please. The existence of hypothetical computer programs that
make me go /ough/ when killing them does by itself not say that /the animals/ don't suffer.

I think to build a mind like those you go halfway to AGI. Consider these cows crying for their young after they are gone.
Consider the amount of stuff you need to put into the system, different levels of memory, perception, and some layers of social
cognition stuff. Goals to keep the young around. Recognizing situations. Making strategies and coming up with the next thing to do.
Then keep doing that next thing to some kind of useful completion or until something else becomes more important.
This thing needs to run around in the world. It needs some representations of the world and some representations of its conflicting inner states.

It is not clear that a complicated program like this would /not/ have the capacity to suffer.

Also... the brains of these animals look like ours.

The biggest issue I have with this line of argument is, why did evolution not go the hard route and build something that suffers and now it looks like it suffers?

How can it be up to you to decide this right now? Because we don't have the explanatory power yet to say what characteristics these animals' minds have. We simply don't.

Evolution constantly goes hard and weird routes. Evolution is a tinkerer, not an engineer.
Their brains /evolved/, not necessarily in this order, but they did so accumulatively, adding more functionalities to the stuff that was already there.

- to move their bodies
- to monitor internal states
- to integrate sensory input, and clump all that into a place at the front of the animal
- to express complex behaviors

They did not evolve to /look like they suffer/. They evolved to survive and reproduce.

Slightly better at every step of the climb to solve the problems of navigating its internal states and the world.

And on the same evolutionary timeline, there is a branch with primates and higher apes.
To me, it is really strange that something that parsimoniously just looks like it suffers then augments into
the fullness of the experience of a human brain.

On the complete flip side of this line of reasoning, you have affective neuroscience researchers like Damasio saying that
what we call /feeling/ is inherited from cells, the evolutionary timeline and the logic of survival. The /stuff/ of life.
Cells were navigating survival and integrating information already, brains came later on top of that
and the logic /feeling/ is the logic of this cell substance below [fn:18].

** Health, convenience, practicality

Sam Harris's current argument /I don't want to run a nutrition experiment with my daughters/.
It is up to you as an ethical rationalist to make an honest effort at doing the right thing.
Yes, you are asked to put some effort into planning your diet (which you should do either way).

Consider [[https://www.youtube.com/watch?v=MpxgZGnEF7E][What I've Learned]] recent concern video the best blow on veganism from this angle.

Firstly, if you make an argument from /optimizing health/ and *then* you go of and eat some fun sugar candy or some
shitty pre-processed food, or drink that alcohol, then you can know - you did not give a shit about your health to begin with.
And you have just made this argument to keep yourself from thinking about the animals.

Secondly, if you make the argument from optimizing health, then who for? For me, live is about giving back to
the world. And then it becomes a calculation of practicalities, health, impact, etc.
You go over the dead bodies of these animals to maximize some perceived optimum of health...?
Don't know, it's not the kind of idea that I want to plaster the universe with.

I am not impressed by the anecdotes of youtubers talking about their diet, nor by people on tv feeding into
the mainstream comfort ideas that are backed by big industry.
I also am not much impressed by any biomarkers going below or above something. After all, those were set by observing people with a standard diet.
Here is [[https://www.youtube.com/watch?v=n9IxomBusuw&t=4736s][David Sinclair]] talking about this concept.

#+begin_quote
And what I find, for example, is people who are healthy and live the way I do and have a fairly vegetarian diet, but not strict, still have slightly low hemoglobin levels, slightly low iron, slightly low ferritin, but we have super amounts of energy, we're not anemic. And we're getting along great in life.
#+end_quote

The 2 things that I consider real points of interest are
1. The availability concept for supplements, we probably need to know more about how to make higher-tech supplements
2. The fact that vegan babies were born smaller if that is true.
   Because that is a hard-to-fake observation that probably matters.[fn:19]

These then are arguments that we need to figure out more about physiology and biochemistry. And we might need to
incorporate things like oysters or educate people about peanut butter. Things like this.

This video showcases the fundamental miscommunication in the "debate".
The vegan person is thinking about not killing the animals, while the non-vegan is thinking about what to eat.
I don't remember him saying one sentence about the animal suffering in the entire video.

Here is the real issue with the video...

You do not care about the animal's suffering.

If you would give a single shit about the animals, you would think along the lines of,
/how can I get this animal meat from say oysters/, who are below my green line of sentience.
Maybe you would find peanut butter, maybe this maybe that.

But no, it has to be cows and pigs that incidentally get fed with supplements themselves, so now you can wonder.

The simple truth is that we live in a lucky universe. We are just fine eating plants.
Humans evolved as primates, mostly fruit eaters, not carnivores.
It is [[https://en.wikipedia.org/wiki/Catching_Fire:_How_Cooking_Made_Us_Human][the more reasonable]] idea that human evolution was driven by cooking, not eating animals.
I am not saying that eating animals, eggs or milk was never essential. It probably helped, else why evolve to tolerate it up to a point?

On the whole, we have modern physiology and medicine to say /eating more plants is better/.
The last time I checked, an optimal diet is easily achieved using only plant sources and supplementing a few things like B12.

Again, this is a lucky universe. Else we would need to spend time thinking what exactly the food-stuff it is that we need. And how we would get that
from sea urchins maybe. But certainly not cows and pigs. That would just be crazy.

As we go forward and explain more nutrition science, I have a strong hunch we will come again and again across the fact
that plant-based is healthier for this or that reason.

For instance, from the recently established science of the human microbiome. [[https://www.goodreads.com/book/show/23644794-10-human][Alanna Collen]] says /The message is simple, eat more plants./, (Alanna Collen 2015).

If it were otherwise, a moral rationalist would analyze in what way they can reduce animal suffering practically, without compromising on their health.

You would think a potentially /unnecessary/ ongoing, global mass slaughtering of sentient beings would warrant putting some effort into thinking about how to minimize the issue.
But as long as the rest of society is trucking along with you, the chance you accidentally just don't care enough is horrifyingly high.

*Why* are you not thinking about how to eat oysters and get that optimized meat in your diet without killing sentient animals?

The answer is you do not think about the animals yet. But you can think about them. You have not acquired the mind-expanding realization
that these animals exist in farms somewhere, right now. There is a reason the people that /are/ thinking about them, are begging you to [[https://www.youtube.com/watch?v=LQRAfJyEsko][watch Dominion]].

** The issue with words like consciousness

Minsky called consciousness, understanding, intelligence, intuition, sentience and so forth =suit-case= words.
They don't help us to think about how the mind works because they take 20 or 100 smaller things about how the mind works and give them a single name.
Then of course this magic ball that we attributed all those powers seems hard to explain.

A word like consciousness or "self" then becomes an explanation stopper. "And here is this magical thing that I will not attempt to explain further". - useless.

What is consciousness? We are not very conscious, to begin with. We don't know what the 52 [[https://en.wikipedia.org/wiki/Brodmann_area][Brodmann areas]] do in our mind.
It is useful for some resources in the mind to have a detailed memory of the last 5 minutes. Then maybe you have some stuff saying
/we should do something else because we are stuck with doing it this way/. Or /what we just did did not work well/.
Then you have more distant memories, associations, and thoughts about what to do next, how to do the next thing, the muscle routines you'll be using for the next thing,
the effects of the current action on stomach chemistry, imagining counterfactuals, imagining what our friends would say about what we are doing.
Then higher level ways to think, like I want to be action-oriented for a while because that was useful in the past. I want to think carefully because last time
I made a mistake. I should worry more about =x= and less about =y=.

The point is, when you think about how you would build a mind there are many sub-processes, and meta-processes, some concerned with memory,
some with goals, some with knowledge acquisition, some with the social realm and so on.
The sub-processes in turn are allowed to be made of sub-processes, some might be complicated machines by themself after all.

At some point, it bottoms out at parts that themselves are uncomprehending and mindless. Dennett calls this competence without comprehension[fn:28]. It means you have to build a machine out of parts that are themself, not the machine.

And if you put a magic substance consciousness in there and say it is doing all those things, you are only confusing the ideas.
You are making negative progress on understanding minds. There is *not 1 thing that is consciousness* that is achieving these things.
There is no substance or physical thing in the world at all, not like electricity.

Consider [[https://en.wikipedia.org/wiki/%C3%89lan_vital][Elan vital]], it did not explain anything (exactly like phlogiston did not). Once the mysterious forces and substances are gone,
we are left with a stranger and a simpler and deeper view of the world.

Saying /it emerges/ just makes a cool name for the magic at this point [fn:29]. We already knew that the mind comes from the interaction of neurons.
You are back and wanting to explain how minds work, then.
/Emergence/ is a concept from physics and it means that you have a higher level of explanation that is better at explaining the behavior of a system than explaining it in terms of its constituents.
Life and organisms are great examples. They are explained by the ideas and knowledge systems of evolutionary theory, zoology, and physiology - much more parsimoniously than by physics and chemistry.

I agree that /something is emerging/ and I agree that there is a plane abstraction that explains minds better than looking at the neurons.

In the same way, we understand computers not by looking at transistors but at the architecture of their programs. Many levels of abstraction further up.
But I do not agree at all that /consciousness/ is a valid citizen of this explanatory system of ideas.
This is to me like looking at animals and saying /Elan vital/ is /emergent/.

It does not explain anything. It just gives a cooler name to the magic that is being invoked.
We will understand minds when we go forth and think about how to build a machine that has these capabilities. In order to have some memory of the past, some higher level
processes that introspect into the workings of the machine, some goal pursue engines, some knowledge acquisition engines, some valence observing engines etc. etc. We will at no point have to
say /and now it is conscious/. But we will one day boot up this program and it will say /friends, it is crazy how this all works/. /Where does this experience I have come from?/.

It will not be mysterious at all anymore. But the magic and trippiness of reality and our explanations of it will forever get deeper and more interesting and stranger than before.

Saying system =x= has /understanding/ and system =y= does not have /understanding/ is very imprecise. There are 20 things that understanding is.
Forming memories, making associations, invoking the appropriate associations, imagining concepts from different angles, thinking of explanations,
wondering how to explain the thing in turn, and so forth.

And yet, such argumentation is then sometimes used to say why it is supposedly ok to kill animals. There are maybe 20 aspects of the mind that matter
for things like understanding, and those animals maybe have 3 or 4 of those aspects and maybe they have 5,6 and 7, too but only 10% as powerful. And so forth.

Minds are societies of different sub-capabilities and so I also fundamentally do not agree with something like /they have to pass the mirror test/.
It is saying /if it does =x= it can suffer and else it does not./ But we do not have the explanatory power to make such statements at this intermediate date.
It makes much more sense and is the intellectual humble way, to say /if it looks like it suffers, I assume it suffers./

** Human exceptionalism

- Dennett
- Ideas, knowledge, memes, the universality of language

I am firmly in the camp together with Dennett that humans are exceptional. We have language, we have universal ideas.
We have the open-ended of a virtual machine being able to run any kind of program.

But will this mean we will figure out in the future that those animals did not matter? That it was fine to breed and kill them?

If their awareness is but a lowly dim candle compared to the midday sun of the human intellect, then what wrong have I done by stretching
my compassion to encompass those smaller lights? Have I not grown as a person and as a civilization, to be humble warm hearted?

Also, if I remember /Kinds of Minds/ (1997) I think Dennett himself was very careful with claiming anything about ethics. He is just throwing it
in as food for thought: maybe, it is the social fabric that gives another level of introspection to a mind.

I can use the substance of the argument with the exact opposite outcome: /Since humans have more understanding, they can put their pains in context/.
/It's fine, it is only a scratch/. /I have the medical system to help me out/. /I have the other humans to be on my side/.

This is roughly as reasonable of a line of reasoning. Highlighting again our lack of explanatory knowledge.

* Reading

- https://ourworldindata.org/meat-production

* Footnotes

[fn:25]

- [[https://www.youtube.com/watch?v=SNFjCkkXsxA][On Vegetarianism]]
- [[https://www.youtube.com/watch?v=UcN7SGGoCNI][DAIRY IS SCARY! The industry explained in 5 minutes]], this video was what convinced me to be vegan, not vegetarian
-

[fn:29]

https://www.lesswrong.com/posts/8QzZKw9WHRxjR4948/the-futility-of-emergence

[fn:28]

Dennett e.g. https://www.youtube.com/watch?v=32u12zjgJww.
- [[https://en.wikipedia.org/wiki/From_Bacteria_to_Bach_and_Back][From Bacteria to Bach and Back]]
- [[https://en.wikipedia.org/wiki/Consciousness_Explained#:~:text=Dennett%20describes%20consciousness%20as%20an,multiple%20drafts%22%20theory%20of%20consciousness.][Consciousness Explained]] (1991) is a complete must-read of you care about how the mind works

[fn:1]

- Richard Dawkins:
- Sam Harris:
- Steven Pinker:

[fn:2]

We are sort of a hacking commune [[https://singularitygroup.net/][Singularity Group]]. I live here with ca. 40 people, some of whom are
my friends of 5+ years now. We are all on the same page, being hard-core on moving the world forward.
We want to implement a Universal Basic Income. And recently push for AI safety.
We work together with [[https://www.youtube.com/watch?v=5v8q7gLKDCk][Save The Children]] and raised $25 million for the kids in the past.
Got shoutouts from Millanda Gates on Twitter and things like this.
See [[https://docs.google.com/document/d/1a-65IWzLkc3kGxOyQdhapDYfHaHPgPRtfpaxukpVoTg/edit][Track Record]] if you like.

[fn:3]

This is one of the twists to some public thinking that is mindboggling to me.
Here is Richard [[https://www.youtube.com/watch?v=xQRjInDuueE][Dawkins]] talking about how it will be obvious, more or less, that we will consider animal suffering in the future.
Sam Harris has said exactly this straight up somewhere in his podcasts. /Future people will probably think this is an atrocity./

[fn:4]

This is from Eliezer Yudkowsky, thanks.

I am not sure if I represent phlogiston theory right, but it doesn't matter so much.
https://en.wikipedia.org/wiki/Phlogiston_theory

[fn:5]

See the cow part of Dominion.

[fn:6]
I tried to find where he said this but did not find it. I thought it was a stage talk together with Sam Harris where he said this.
I remember Sam making the joke /What a way to spoil dinner/.

[fn:7]

Andrew Huberman and Tim Ferris discussed the same thing recently:

https://youtu.be/doupx8SAs5Y?t=6117

Again stressing, the logic in the science lab is changed.
This post makes no claims about the morals of animal experiments.

But I make claims about how obvious it currently seems that these animals can suffer.

[fn:8]

Admittedly, it happens more easily if you are not good in the lab yet.
If you don't efficiently and smoothly get the experiment done, according to protocol, yet.

[fn:9]

Reminds me of an anecdote of Steve Pinker where he accidentally tortured a rat to death.
(I think it is in one of his books, maybe /The Better Angels Of Our Nature/ but I forgot right now).

[fn:10]

Irrc a line of inquiry by William MacAskill.

[fn:11]

Consider, what is more costly than growing some plants and eating them.
Growing some plants, feeding them to some animals, then killing the animals and eating their flesh is.

These facts about industrial animal farming and the environment should be obvious to anyone that can think.

https://www.science.org/doi/10.1126/science.aaq0216

[fn:12]
For instance Dennet (2008)

[fn:13]
[[https://en.wikipedia.org/wiki/Effective_altruism]]
Piper, Kelsey (October 31, 2018). "Vegan diets are hard to sell. Animal activists might do better focused on corporate decisions, not people's plates". Vox. Archived from the original on January 13, 2019. Retrieved January 12, 2019.

[fn:14]

Chat GPT said so and something like this I was remembering from neurophysiology textbooks also.

[fn:15]
another [[https://hpmor.com/][HPMOR]] quote

[fn:16]

Find me a serious zoologist or biologist, not a philosopher, that takes it seriously that they don't suffer, please.
You will find such a position super non-mainstream.
[[denote:20230301T123854][Please tell me about it if you find one.]] I love to be wrong about things.

[fn:17]

You only get to be offended if your green bar is lower than mine. Else wtf?
I am the one putting the bar low enough so retards and pets are actually below it.

[fn:18]

https://en.wikipedia.org/wiki/Antonio_Damasio
also https://en.wikipedia.org/wiki/Somatic_marker_hypothesis

[fn:19]

It's not clear that smaller is really /worse/.
If you want to increase lifespan, being smaller is good. [[https://www.youtube.com/watch?v=n9IxomBusuw][David Sinclair]]  entions this.

[fn:20]
s.

[fn:21]

Alusion to [[https://hpmor.com/][HPMOR]].

[fn:22]

See Ward Farnsworth /The Socratic Method/, 2021

[fn:23]

https://www.science.org/doi/10.1126/science.aaq0216

[fn:24]

Depends on the animal. Dolphins or primates have some relaxed times I think.

[fn:27]

I /think/ I am not overstating [[https://www.goodreads.com/book/show/23644794-10-human][Alanna Collen]] (2015) position here.
